#managining actuator endpoints both include and exclude also base-path settings
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:  beans, caches, conditions, env, flyway, health, httptrace , integrationgraph, loggers, liquibase, metrics, mappings, scheduletasks, sessions, shutdown, threaddump, info
        exclude: auditevents, configprops
  info:
    env:
      enabled: true
    app:
      name: "MY INFO APP"
      description: "A Spring Boot application"
      version: "1.0"
# defining @value properties
coach:
  name: "Linux Profile"
player:
  name: "linus Torvalrds"

# JDBC Settings
# Setting Spring Intalization to LAZY by default
spring:
  profile:
    active: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      pool-name: MyHikariCPool
    continue-on-error: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: root
      password: root
  sql:
    init:
      continue-on-error: true
  # main:
  #lazy-initialization: true

# Server configuration and configuration
server:
  port: 8080
  servlet:
    context-path: /myapp
  session:
    timeout: 5m

# Logging level settings
logging:
  level:
    org.springframework: INFO
    hibernate: TRACE
    com.springboot.demo.mycoolapp: INFO
  file: coolapp.log
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
